language: python
python:
  - 3.5

env:
  global:
    - CONDA_INSTALL_PATH=$HOME/conda
    - PROJ_DIR=$HOME/miniconda
  matrix:
    - PYTHON_VERSION='3.5'
    - PYTHON_VERSION='2.7'

sudo: required

#cache:
#  apt: true
#  pip: true
#  directories:
#    - $PROJ_DIR

before_install:
  - ls /etc/profile.d/

install:
  - export MINICONDA_VER='4.2.12'
  - export MINICONDA_VARIANT='3'
  - export OS_TYPE="Linux-x86_64.sh"
  - sudo chmod -R 755 /etc/profile.d
  - ls -la /etc/profile.d/
  - wget -O - https://raw.githubusercontent.com/bomboradata/bootstrap-conda/master/bootstrap-conda.sh | bash
  - source /etc/profile
  - ls -la /etc/profile.d/
  #- source /etc/profile.d/conda.sh
  - echo "$PATH"
  - echo "$PWD"
  - ls -la $HOME
  - conda update --all --yes --quiet
  - conda info
  - conda list
  - echo "$PATH"
  - echo "$PWD"

after_install:
  - ls /etc/profile.d/

script:
  - conda create --yes --quiet --name=dragnet-$PYTHON_VERSION python=$PYTHON_VERSION
  - conda env update --quiet --name=dragnet-$PYTHON_VERSION --file=./env/env_dragnet.yml
  - conda info
  - conda list
  - source activate dragnet-$PYTHON_VERSION
  - make install-pip
  - make test
