language: generic
sudo: required

os:
  - linux
  - osx

env:
  matrix:
    - PYTHON=2.7
    - PYTHON=3.5
    - PYTHON=3.6

install:
  # use miniconda until travis supports python on osx
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O ~/miniconda.sh;
    elif [ "$TRAVIS_OS_NAME" == "linux" ]; then
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh;
    fi
  - bash ~/miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda create --yes -n python-env python=$PYTHON
  - source activate python-env

  - pip install -r requirements.txt
  - pip list
  - pip install .

after_install:
  - pip list

script:
  - pytest
