language: python
python:
  - 2.7
script: make test
virtualenv:
  system_site_packages: true
cache:
  - apt
  - pip
install:
  - sudo apt-get -y install libxslt-dev libxml2-dev python-numpy python-scipy python-matplotlib
  - pip install -r requirements.txt
  - git clone https://github.com/seomoz/mozsci.git
  - pushd mozsci
  - pip install -r requirements.txt
  - make install
  - popd
  - python setup.py build_ext --inplace
